from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None

def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table("restaurants",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("name",sa.String(255),nullable=False),sa.Column("whatsapp_number",sa.String(50),nullable=False,unique=True),sa.Column("timezone",sa.String(50),server_default="Asia/Karachi"),sa.Column("delivery_radius_km",sa.Numeric(5,2)),sa.Column("delivery_fee",sa.Numeric(10,2),server_default="0"),sa.Column("min_order_amount",sa.Numeric(10,2),server_default="0"),sa.Column("opening_time",sa.Time()),sa.Column("closing_time",sa.Time()),sa.Column("is_active",sa.Boolean(),server_default=sa.true()),sa.Column("brand_voice",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")))
    op.create_table("menu_categories",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("display_order",sa.Integer(),server_default="0"))
    op.create_table("menu_items",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("category_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("menu_categories.id")),sa.Column("name",sa.String(255),nullable=False),sa.Column("description",sa.Text()),sa.Column("base_price",sa.Numeric(10,2),nullable=False),sa.Column("is_available",sa.Boolean(),server_default=sa.true()),sa.Column("variants",postgresql.JSONB(),server_default="[]"),sa.Column("addons",postgresql.JSONB(),server_default="[]"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")))
    op.create_table("customers",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("phone",sa.String(50),nullable=False),sa.Column("name",sa.String(255)),sa.Column("saved_address",sa.Text()),sa.Column("total_orders",sa.Integer(),server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")),sa.UniqueConstraint("restaurant_id","phone"))
    op.create_table("conversations",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("customer_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("customers.id"),nullable=False),sa.Column("status",sa.String(50),server_default="active"),sa.Column("order_stage",sa.String(50),server_default="browsing"),sa.Column("started_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")),sa.Column("ended_at",sa.DateTime(timezone=True)),sa.Column("escalated_reason",sa.Text()))
    op.create_table("messages",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("conversations.id"),nullable=False),sa.Column("direction",sa.String(20),nullable=False),sa.Column("role",sa.String(20),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("whatsapp_message_id",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")))
    op.create_table("orders",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("customer_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("customers.id"),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("conversations.id")),sa.Column("items",postgresql.JSONB(),nullable=False),sa.Column("subtotal",sa.Numeric(10,2),nullable=False),sa.Column("delivery_fee",sa.Numeric(10,2),server_default="0"),sa.Column("total",sa.Numeric(10,2),nullable=False),sa.Column("delivery_address",sa.Text(),nullable=False),sa.Column("payment_method",sa.String(50),nullable=False),sa.Column("status",sa.String(50),server_default="pending"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")))
    op.create_table("escalations",sa.Column("id",postgresql.UUID(as_uuid=True),server_default=sa.text("gen_random_uuid()"),primary_key=True),sa.Column("restaurant_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("restaurants.id"),nullable=False),sa.Column("conversation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("conversations.id"),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("status",sa.String(50),server_default="open"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("NOW()")),sa.Column("resolved_at",sa.DateTime(timezone=True)))
    op.create_index("idx_customers_restaurant_phone","customers",["restaurant_id","phone"]);op.create_index("idx_conversations_restaurant","conversations",["restaurant_id"]);op.create_index("idx_conversations_status","conversations",["status"]);op.create_index("idx_messages_conversation","messages",["conversation_id"]);op.create_index("idx_orders_restaurant","orders",["restaurant_id"]);op.create_index("idx_orders_status","orders",["status"]);op.create_index("idx_menu_items_restaurant","menu_items",["restaurant_id"])

def downgrade():
    for n,t in [("idx_menu_items_restaurant","menu_items"),("idx_orders_status","orders"),("idx_orders_restaurant","orders"),("idx_messages_conversation","messages"),("idx_conversations_status","conversations"),("idx_conversations_restaurant","conversations"),("idx_customers_restaurant_phone","customers")]:op.drop_index(n,table_name=t)
    for t in ["escalations","orders","messages","conversations","customers","menu_items","menu_categories","restaurants"]:op.drop_table(t)
